<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "typo_paradise"
 *
 * Auto generated by Extension Builder 2014-12-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Typo Paradise',
	'description' => 'TYPO3 6.2 Extension for building web projects based on Twitter Bootstrap, Bower and Grunt.',
	'category' => 'templates',
	'author' => 'Thomas Schlich',
	'author_email' => 't.schlich@mad-world.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);